### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
import numpy as np

In [15]:
### code here
a1 = np.array([[3.0,2.0,np.nan,1.0],[10.0,12.0,10.0,9.0],[5.0,np.nan,1.0,np.nan]])

print("Original array:\n",a1)

print("\nFind the missing data of the said array:\n",np.where(np.isnan(a1),True,False))

Original array:
 [[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [34]:
### code here 

a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
c = np.arange(0,10).reshape(2,5)
d = np.arange(1,10).reshape(3,3)
e = np.arange(1,10).reshape(3,3,1)

print("array a :\n",a)
print("array b :\n",b)
print("array c :\n",c)
print("array d :\n",d)
print("array e :\n",e)
print("if a and b are equal?: ",np.array_equal(a,b))
print("if a and c are equal?: ",np.array_equal(a,c))
print("if a and d are equal?: ",np.array_equal(a,d))
print("if b and c are equal?: ",np.array_equal(b,c))
print("if a and e are equal?: ",np.array_equal(a,e))

array a :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array b :
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
array c :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array e :
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
if a and b are equal?:  False
if a and c are equal?:  False
if a and d are equal?:  True
if b and c are equal?:  False
if a and e are equal?:  False


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [50]:
## code here

arr1  = np.random.randint(0,15,size=(4,4))


print("Original array:\n",arr1)

#### Method 1 ############
arr1[[0,3]] = arr1[[3,0]]
print("\nNew array after swapping first and last rows of the said array:\n",arr1)




Original array:
 [[ 9  2  0 13]
 [ 2  5  9 13]
 [ 4  0 12  0]
 [ 2 12  7 10]]

New array after swapping first and last rows of the said array:
 [[ 2 12  7 10]
 [ 2  5  9 13]
 [ 4  0 12  0]
 [ 9  2  0 13]]


In [49]:

arr1  = np.random.randint(0,15,size=(4,4))


print("Original array:\n",arr1)
#### Method 2 ############
arr2 = np.copy(arr1)
arr2 [0] =arr1 [3]

arr2[3] = arr1[0]
print("\nNew array after swapping first and last rows of the said array:\n",arr2)

Original array:
 [[ 0 11  1  0]
 [ 8  3  3  7]
 [ 7  1  8  6]
 [ 5  8 11  0]]

New array after swapping first and last rows of the said array:
 [[ 5  8 11  0]
 [ 8  3  3  7]
 [ 7  1  8  6]
 [ 0 11  1  0]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [52]:
#### code here
li = [1,2,3,4]
t = (5,6,7,8)

print("Numpy array from list:\n",np.array(li))
print("Numpy array from tuple:\n",np.array(t))

Numpy array from list:
 [1 2 3 4]
Numpy array from tuple:
 [5 6 7 8]


###### 5. Write a NumPy program to find common values between two arrays.

In [54]:
### code here

a1 = np.arange(0,10)
a2 = np.arange(5,15)

print("Array 1  is :\n",a1)
print("Array 2  is :\n",a2)

print("Common elements in the two given arrays are : ",np.intersect1d(a1,a2))

Array 1  is :
 [0 1 2 3 4 5 6 7 8 9]
Array 2  is :
 [ 5  6  7  8  9 10 11 12 13 14]
Common elements in the two given arrays are :  [5 6 7 8 9]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [57]:
### code here
arr3 = np.arange(1,7).reshape(3,2)
print("Original array :\n",arr3)
print("Reshaped array :\n",arr3.reshape(2,3))

Original array :
 [[1 2]
 [3 4]
 [5 6]]
Reshaped array :
 [[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [63]:
### code here
arr4 = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print("Original array:\n",arr4)
print("Frequency of unique values of the said array:\n",np.asarray((np.unique(arr4,return_counts=True))))


Original array:
 [10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
 [[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [73]:
### code here
p = np.array([[0,0,0],[1,2,3],[4,5,6]])
q = np.array([10,11,12])

print("Original arrays:\nArray-1",p,"\nArray-2\n",q)
print("\nNew Array:\n",p+q)

Original arrays:
Array-1 [[0 0 0]
 [1 2 3]
 [4 5 6]] 
Array-2
 [10 11 12]

New Array:
 [[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [75]:
### code here
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [80]:
## code here
arr5 = np.arange(0,16).reshape(4,4)
print("Original array:\n",arr5)

print("Extracted data: Third and fourth elements of the first and second rows \n",arr5[0:2,2:])

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extracted data: Third and fourth elements of the first and second rows 
 [[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [101]:
### code here
import numpy as np
today = np.datetime64('today','D')
print("today: ",today)
print("yesterday: ",today - np.timedelta64(1,'D'))
print("tomorrow: ",today + np.timedelta64(1,'D'))

today:  2022-09-28
yesterday:  2022-09-27
tomorrow:  2022-09-29


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [117]:
## code here
import numpy as np

first_monday = np.busday_offset('2017-05', 0, roll='forward',weekmask='Mon')
print(first_monday)

2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
